### ISSUE TITLE
Cannot Find Module

### ISSUE THREAD

**Issue by OneKinkyKid** [rageb-insane/insane-auto-dueler#1]
when running after the first use I get the following error:
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '../utils/slave2ID.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\William\Documents\pokecord-catcher-master\SPAMMING BOTS\insane-auto-dueler-master\utils\slave2.js:11:16)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
Press any key to continue . . .
 Unable to run the bot in any fashion as of now

**Comment by OneKinkyKid** [comment]
if you make a slave2ID then give it its id you get the following code:
(node:9276) UnhandledPromiseRejectionWarning: Error: Incorrect login details were provided.
    at WebSocketConnection.client.ws.connection.once.event (C:\Users\William\Documents\pokecord-catcher-master\SPAMMING BOTS\insane-auto-dueler-master\node_modules\discord.js\src\client\ClientManager.js:47:41)
    at Object.onceWrapper (events.js:277:13)
    at WebSocketConnection.emit (events.js:189:13)
    at WebSocketConnection.onClose (C:\Users\William\Documents\pokecord-catcher-master\SPAMMING BOTS\insane-auto-dueler-master\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:390:10)
    at WebSocket.onClose (C:\Users\William\Documents\pokecord-catcher-master\SPAMMING BOTS\insane-auto-dueler-master\node_modules\ws\lib\event-target.js:124:16)
    at WebSocket.emit (events.js:189:13)
    at _receiver.cleanup (C:\Users\William\Documents\pokecord-catcher-master\SPAMMING BOTS\insane-auto-dueler-master\node_modules\ws\lib\websocket.js:220:12)
    at Receiver.cleanup (C:\Users\William\Documents\pokecord-catcher-master\SPAMMING BOTS\insane-auto-dueler-master\node_modules\ws\lib\receiver.js:535:15)
    at WebSocket.finalize (C:\Users\William\Documents\pokecord-catcher-master\SPAMMING BOTS\insane-auto-dueler-master\node_modules\ws\lib\websocket.js:206:20)
    at TLSSocket.emit (events.js:194:15)
(node:9276) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9276) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 4:25 PM : TOTAL REAL SLAVE 1 successfully logged in.
where it wont handle the second login and thus be stuck
